steps:
- name: gcr.io/cloud-builders/docker
  id: docker-compose
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.21.2'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/docker-compose:latest'
  - '.'
- name: gcr.io/cloud-builders/docker
  id: smp_ci
  args:
  - 'build'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
  - '-f'
  - './ops/Dockerfile'
  - '.'

- name: asia.gcr.io/$PROJECT_ID/docker-compose
  wait_for:
  - docker-compose
  - smp_ci
  args:
  - '-f'
  - './ops/docker-compose.yml'
  - 'up'

images:
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
  - 'asia.gcr.io/$PROJECT_ID/docker-compose:latest'
