steps:
- name: gcr.io/cloud-builders/docker
  id: build_smp_ci
  args:
  - 'build'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
  - '-f'
  - './ops/Dockerfile'
  - '.'
- name: gcr.io/cloud-builders/docker
  id: run_ci
  entrypoint: 'bash'
  args:
  - '-c'
  - './ops/ci.sh'

images:
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
