steps:
- name: gcr.io/cloud-builders/docker
  args:
  - 'build'
  - '--build-arg'
  - 'version=1.21.2'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/docker-compose:latest'
  - '.'
- name: gcr.io/cloud-builders/docker
  args:
  - 'build'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
  - '-f'
  - './ops/Dockerfile'
  - '.'
- name: asia.gcr.io/$PROJECT_ID/docker-compose
  waitFor:
  - '-'
  args:
  - '-f'
  - './ops/docker-compose.yml'
  - 'up'
images:
  - 'asia.gcr.io/$PROJECT_ID/smp_ci'
  - 'asia.gcr.io/$PROJECT_ID/docker-compose:latest'
